[repos]

general = 'https://github.com/ansible-collections/community.general.git'
proxmox_upstream = 'https://github.com/ansible-collections/community.proxmox.git'
proxmox_origin = 'git@github.com:WaitingAtTheCrossroads/community.proxmox.git'

files = [
  'plugins/connection/proxmox_pct_remote.py',
  'plugins/doc_fragments/proxmox.py',
  'plugins/inventory/proxmox.py',
  'plugins/module_utils/proxmox.py',
  'plugins/module_utils/version.py',

  # glob seems to not actually follow renames...?
  'plugins/modules/proxmox*',
  'plugins/modules/proxmox_backup_info.py',
  'plugins/modules/proxmox_backup.py',
  'plugins/modules/proxmox_disk.py',
  'plugins/modules/proxmox_domain_info.py',
  'plugins/modules/proxmox_group_info.py',
  'plugins/modules/proxmox_kvm.py',
  'plugins/modules/proxmox_nic.py',
  'plugins/modules/proxmox_node_info.py',
  'plugins/modules/proxmox_pool_member.py',
  'plugins/modules/proxmox_pool.py',
  'plugins/modules/proxmox_snap.py',
  'plugins/modules/proxmox_storage_contents_info.py',
  'plugins/modules/proxmox_storage_info.py',
  'plugins/modules/proxmox_tasks_info.py',
  'plugins/modules/proxmox_template.py',
  'plugins/modules/proxmox_user_info.py',
  'plugins/modules/proxmox_vm_info.py',
  'plugins/modules/proxmox.py',

  # glob seems to not actually follow renames...?
  'tests/integration/targets/proxmox*',
  'tests/integration/targets/proxmox/',
  'tests/integration/targets/proxmox_pool/',
  'tests/integration/targets/proxmox_template/',

  'tests/unit/plugins/connection/test_proxmox_pct_remote.py',
  'tests/unit/plugins/inventory/test_proxmox.py',

  # glob seems to not actually follow renames...?
  'tests/unit/plugins/modules/test_proxmox*',
  'tests/unit/plugins/modules/test_proxmox_backup_info.py',
  'tests/unit/plugins/modules/test_proxmox_backup.py',
  'tests/unit/plugins/modules/test_proxmox_kvm.py',
  'tests/unit/plugins/modules/test_proxmox_snap.py',
  'tests/unit/plugins/modules/test_proxmox_storage_contents_info.py',
  'tests/unit/plugins/modules/test_proxmox_tasks_info.py',
  'tests/unit/plugins/modules/test_proxmox_template.py',
  'tests/unit/plugins/modules/test_proxmox_vm_info.py',
]

# I'm pretty sure git picked up renames when unrelated files with the same
# content where added/removed at the same time.
false_positives = [
  'plugins/action/__init__.py',
  'tests/integration/targets/ansible_galaxy_install/meta/main.yml',
  'tests/integration/targets/cloud_init_data_facts/meta/main.yml',
  'tests/integration/targets/cpanm/meta/main.yml',
  'tests/integration/targets/git_config/files/gitconfig',
  'tests/integration/targets/ini_file/meta/main.yml',
  'tests/integration/targets/iso_extract/files/test.iso.license',
]
